#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2011 OpenWrt.org
#set -x
START=95
STOP=10

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_STOP_TIME=9

error() {
	echo "${initscript}:" "$@" 1>&2
}

start() {
        if [ -f /root/mysqlinit ]; then
           /bin/rm -fR /root/mysql/*
           /usr/bin/mysql_install_db --force
        fi

	local datadir=$(sed -n -e "s/^[[:space:]]*datadir[[:space:]]*=[[:space:]]*[\"']\?\([^\"']*\)[\"']\?/\1/p" /etc/my.cnf)
	if [ ! -d "$datadir" ]; then
		error "Error: datadir '$datadir' in /etc/my.cnf doesn't exist"
		return 1
	fi
	if [ ! -f "$datadir/mysql/tables_priv.MYD" ]; then
		error "Error: I didn't detect a privileges table, you might need to run mysql_install_db --force to initialize the system tables"
		return 1
	fi
 
        if [ -f /root/mysqlinit ]; then
           mv /root/mysqlinit /root/mysqlinit.org
           service_start /usr/bin/mysqld --init-file=/root/mysqlinit.org
        else
	   service_start /usr/bin/mysqld
        fi
}

stop() {
	service_stop /usr/bin/mysqld
}
