#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
#set -x
STOP=99
stop() {
	sync
        #/bin/date >> /sdcard/xx.0
        #/usr/bin/lsof /root/hd1 >> /sdcard/xx.0
        #/usr/bin/lsof /root/hd2 >> /sdcard/xx.0
	/bin/umount -a -d -r
}
